version: "3.9"
services:
    mssql:
        image: "mcr.microsoft.com/mssql/server"
        ports:
         - "1433:1433"
        environment:
            SA_PASSWORD: "al@123Students"
            ACCEPT_EULA: "Y"